name: Configure Pantheon
description: Configure the context for Pantheon authentication and access.
inputs:
  PANTHEON_MACHINE_TOKEN:
    description: "The Machine Token associated with the Pantheon account with access to the sites."
    required: true
  PANTHEON_PRIVATE_SSH_KEY:
    description: "The private SSH key (in PEM format) associated with the Pantheon account."
    require: true
  PANTHEON_BLUE_SITE_ID:
    description: "The site UUID of the Blue site on Pantheon."
    require: true
  PANTHEON_BLUE_SITE_ENV:
    description: "The source environment of the Blue site on Pantheon."
    require: true
  PANTHEON_GREEN_SITE_ID:
    description: "The site UUID the Green site on Pantheon."
    require: true
  PANTHEON_GREEN_SITE_ENV:
    description: "The target environment of the Green site on Pantheon."
    require: true

outputs:
  TMP_DIR_NAME:
    description: "Temporary directory workspace name"
    value: ${{ steps.configure-pantheon-variables.outputs.TMP_DIR_NAME }}
  TMP_DIR_PATH:
    description: "Temporary directory workspace path"
    value: ${{ steps.configure-pantheon-variables.outputs.TMP_DIR_PATH }}
  MOUNT_PATH:
    description: "Path to mount remote dir"
    value: ${{ steps.configure-pantheon-variables.outputs.MOUNT_PATH }}
  BASE_BRANCH:
    description: "Base branch for code sync"
    value: ${{ steps.configure-pantheon-variables.outputs.BASE_BRANCH }}
  IDENTITY_FILE:
    description: "Path to the identity file"
    value: ${{ steps.configure-pantheon-variables.outputs.IDENTITY_FILE }}
  BLUE_SITE:
    description: "Blue site.env"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE }}
  BLUE_SITE_NAME:
    description: "Blue Site name"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_NAME }}
  BLUE_SITE_ENV:
    description: "Blue Site source environment"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_ENV }}
  BLUE_SITE_ID:
    description: "Blue Site UUID"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_ID }}
  BLUE_SITE_REPO:
    description: "Blue Site Git repository url"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_REPO }}
  BLUE_SITE_SFTP_USER:
    description: "Blue Site SFTP User"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_SFTP_USER }}
  BLUE_SITE_SFTP_HOST:
    description: "Blue Site SFTP Host"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_SFTP_HOST }}
  BLUE_SITE_SFTP_PORT:
    description: "Blue Site SFTP Port"
    value: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_SFTP_PORT }}
  GREEN_SITE:
    description: "Green site.env"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE }}
  GREEN_SITE_NAME:
    description: "Green site name"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_NAME }}
  GREEN_SITE_ENV:
    description: "Green Site destination environment"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_ENV }}
  GREEN_SITE_ID:
    description: "Green Site UUID"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_ID }}
  GREEN_SITE_REPO:
    description: "Green Site Git repository url"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_REPO }}
  GREEN_SITE_SFTP_USER:
    description: "Green Site SFTP User"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_SFTP_USER }}
  GREEN_SITE_SFTP_HOST:
    description: "Green Site SFTP Host"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_SFTP_HOST }}
  GREEN_SITE_SFTP_PORT:
    description: "Green Site SFTP Port"
    value: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_SFTP_PORT }}

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.1"

    - id: prepare-ssh-config
      name: Prepare SSH config
      shell: bash
      run: |
        echo 'SSH_CONFIG<<EOF' >> $GITHUB_OUTPUT
        echo "Host *.drush.in" >> $GITHUB_OUTPUT
        echo "  StrictHostKeyChecking no" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Configure SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.PANTHEON_PRIVATE_SSH_KEY }}
        config: ${{ steps.prepare-ssh-config.outputs.SSH_CONFIG }}
        known_hosts: " "

    - name: Setup Terminus
      run: ./.github/scripts/setup-terminus.sh
      shell: bash
      env:
        PANTHEON_MACHINE_TOKEN: ${{ inputs.PANTHEON_MACHINE_TOKEN }}

    - id: configure-pantheon-variables
      name: Configure variables
      shell: bash
      run: ./.github/scripts/variables.sh
      env:
        PANTHEON_BLUE_SITE_ENV: ${{ inputs.PANTHEON_BLUE_SITE_ENV }}
        PANTHEON_GREEN_SITE_ENV: ${{ inputs.PANTHEON_GREEN_SITE_ENV }}

    - name: Install apt-get dependencies
      run: sudo apt-get install -y jq rclone sshfs
      shell: bash

    - name: Add Pantheon SSH known hosts
      shell: bash
      run: |
        ssh-keyscan -t rsa -p 2222 "appserver.dev.${BLUE_SITE_ID}.drush.in" >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa -p 2222 "codeserver.dev.${BLUE_SITE_ID}.drush.in" >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa -p 2222 "appserver.dev.${GREEN_SITE_ID}.drush.in" >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa -p 2222 "codeserver.dev.${GREEN_SITE_ID}.drush.in" >> ~/.ssh/known_hosts
      env:
        BLUE_SITE_ID: ${{ steps.configure-pantheon-variables.outputs.BLUE_SITE_NAME }}
        GREEN_SITE_ID: ${{ steps.configure-pantheon-variables.outputs.GREEN_SITE_NAME }}
